CREATE ROLE role_life_aplic NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE role_life_users NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE admin_life LOGIN PASSWORD '4dm1n' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

-- ATRIBUICAO DE PRIVILEGIOS

GRANT role_life_users TO admin_life;
GRANT role_life_aplic TO admin_life;